# Google Cloud Build configuration for Child Health Backend

steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    dir: 'backend'
  
  # Run tests (optional)
  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    dir: 'backend'
    env:
      - 'NODE_ENV=test'
  
  # Build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'child-health-backend'
      - '--source=backend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production'

# Cloud Build service account needs these permissions:
# - Cloud Run Admin
# - Cloud Build Service Account
# - Service Account User

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
